//
//  DailyFactsStorage_EN.swift
//  Persona Code
//
//  Created by Иван Семикин on 11/03/2025.
//

import Foundation

final class DailyFactsStorage_EN {
    static let shared = DailyFactsStorage_EN()
    
    private let wishes = [
        "Human body can distinguish up to 10 million colors.",
        "When you learn something new, new neural connections form in your brain within seconds.",
        "The brain can predict the future by building probability models based on experience.",
        "Your body renews itself every second, replacing about 50 billion cells daily!",
        "During sleep, the brain processes and sorts information, helping to consolidate memories.",
        "A person can survive without food for over a month, but no more than 11 days without sleep.",
        "The brain weighs only 2% of the body mass but consumes 20% of its energy.",
        "The human eye can distinguish up to 1,000 shades of gray.",
        "You use 100% of your brain, but not all areas are active at the same time.",
        "Your skin renews itself every 28 days.",
        "Bones are stronger than steel. The femur can withstand up to 900 kg of load!",
        "The human nose can distinguish about 1 trillion different scents.",
        "Your stomach renews itself every 3-4 days to prevent self-digestion.",
        "The brain can work even during sleep. Some people find solutions to problems while dreaming.",
        "The human heart beats about 35 million times per year.",
        "Human bones have the ability to self-repair.",
        "When you listen to your favorite music, your brain releases dopamine, causing a sense of happiness.",
        "The brain can change its structure, a phenomenon known as neuroplasticity.",
        "As you grow older, you lose about 50% of your taste receptors.",
        "The human voice is as unique as fingerprints.",
        "Blood vessels in your body, if connected in one line, could wrap around the Earth twice!",
        "Laughter activates around 15 facial muscles.",
        "The brain processes information at a speed of up to 120 meters per second.",
        "A person can distinguish up to 500,000 different sounds.",
        "A human fingertip is so sensitive that it can detect a texture just 13 nanometers in size.",
        "When a person falls in love, the same brain areas are activated as when using drugs.",
        "The human brain generates about 70,000 thoughts per day.",
        "Laughter improves cardiovascular function and reduces stress levels.",
        "Human skin is the largest organ, covering an area of about 2 square meters.",
        "Sleep helps the brain remove toxins accumulated during the day.",
        "Your bones are stronger than concrete, especially the femur.",
        "The brain uses as much energy as a 10-watt light bulb.",
        "When you blink, your brain momentarily turns off vision, but you don’t notice it.",
        "Your stomach produces new mucus every 3-4 days to protect itself from self-digestion.",
        "You spend about 10% of your life blinking.",
        "The brain consumes about 20% of the oxygen that enters the body.",
        "Blood in your body moves at a speed of approximately 7 km/h.",
        "Your hair continues to grow for several hours after death.",
        "The human body produces about a liter of saliva per day.",
        "The strongest muscle in the body is the tongue.",
        "A person can survive without food for up to 40 days, but without water for no more than 3-5 days.",
        "During intense physical activity, the body can release up to 4 liters of sweat per hour.",
        "In a state of stress, pupils dilate to better detect potential danger.",
        "The brain can form memories even in the womb.",
        "Your bones are lighter than water, yet incredibly strong.",
        "The brain has more connections than there are stars in the Milky Way galaxy.",
        "The human nose can remember up to 50,000 different scents.",
        "The feeling of hunger arises when the level of the hormone ghrelin increases in the body.",
        "The fastest muscle in the body is the one responsible for blinking.",
        "The brain can generate new neurons even in adulthood.",
        "Each finger has a unique vein pattern, just like fingerprints.",
        "The human brain can work faster than a supercomputer.",
        "A person takes about 20,000 breaths per day.",
        "The human body contains about 0.2 milligrams of gold.",
        "Bones become denser in response to physical activity.",
        "Sleep improves the brain’s ability to solve complex problems.",
        "Human skin contains about 5 million pain receptors.",
        "Every cell in the body receives nutrients from the blood within 60 seconds.",
        "The brain releases more endorphins during hugs than when eating chocolate.",
        "The adult human body contains about 5 liters of blood.",
        "The liver can regenerate even after 75% of its mass is removed.",
        "Human eyes can distinguish more than 500 shades of a single color.",
        "Every person has a unique biological rhythm of sleep and wakefulness.",
        "The brain can remember up to 5,000 faces.",
        "Each human hair can support up to 100 grams of weight.",
        "The brain’s temperature can rise during intense mental activity.",
        "The body loses about 500 milliliters of water daily just through breathing.",
        "The stomach renews its protective lining every few days.",
        "Human skin regenerates faster than any other tissue.",
        "The human gut contains over 100 trillion bacteria.",
        "The brain can perceive and process speech in just 0.05 seconds.",
        "The human heart can beat even outside the body if oxygen is supplied.",
        "The human ear can detect sounds between 20 Hz and 20,000 Hz.",
        "Skin can detect temperature differences as small as 0.02 degrees.",
        "The brain retains information better when emotions are involved.",
        "Human bones can self-repair after fractures.",
        "The body can adapt to extreme temperatures within weeks.",
        "The brain can process an image seen by the eyes in 13 milliseconds.",
        "The human body can adapt to living in zero gravity.",
        "Your body contains about 37.5 trillion cells.",
        "Blood in the body is completely renewed every 120 days.",
        "The brain generates enough electricity to power a 10-watt light bulb.",
        "Human hair contains traces of gold.",
        "The adult human body contains about 250 grams of salt.",
        "Human nails grow faster on the dominant hand.",
        "Every person has a unique tongue print, like fingerprints.",
        "Human skin can stretch up to twice its normal size.",
        "The body regulates its temperature by sweating.",
        "The human eye can process more than 100 frames per second.",
        "Bones can fully heal after a fracture without leaving scars.",
        "The brain continues to function for several minutes after the heart stops.",
        "The human body contains over 200 different types of cells.",
        "The heart pumps more than 7,500 liters of blood per day.",
        "The body can produce vitamin D when exposed to sunlight.",
        "Lungs can hold up to 6 liters of air.",
        "The human body contains more bacteria than cells.",
        "In cold temperatures, the body shivers to generate heat.",
        "The brain uses about 50% of the glucose that enters the body.",
        "Skin becomes lighter in winter due to reduced melanin production.",
        "Eyes can detect light waves between 380 and 750 nanometers.",
        "Human blood can change color depending on its oxygen content.",
        "Human muscles can contract at speeds of up to 100 m/s.",
        "Sweat has no odor, but bacteria on the skin create it.",
        "The body can naturally destroy cancer cells.",
        "Nerve impulses in the body travel at speeds up to 120 m/s.",
        "The human body can survive without a spleen, but immunity weakens.",
        "The brain stores 2.5 petabytes of information, like 3 million hours of video.",
        "Muscles can handle loads 50 times greater than usual.",
        "The heart pumps 200 million liters of blood in a lifetime, enough to fill 80 pools.",
        "90% of perception is vision, but the brain enhances hearing when vision is lost.",
        "Meditation makes the brain’s gray matter denser, improving memory.",
        "The body produces a painkiller 200 times stronger than morphine.",
        "Lack of sleep reduces memory retention.",
        "The brain reacts faster to negativity as a defense mechanism.",
        "During sleep, the brain actively processes and organizes information.",
        "A person can survive 60 days without food, but no more than 3 without water.",
        "300 million cells die every minute, but just as many are created.",
        "The body can function normally with only one kidney."
    ]
    
    private init() {}
    
    func getRandomFact(excluding lastFact: String?) -> String {
        let filtered = wishes.filter { $0 != lastFact }
        return filtered.randomElement() ?? wishes.randomElement()!
    }
}

