//
//  DailyFactsStorage_PL.swift
//  Persona Code
//
//  Created by Иван Семикин on 11/03/2025.
//

import Foundation

final class DailyFactsStorage_PL {
    static let shared = DailyFactsStorage_PL()
    
    private let allFacts = [
        "Ludzkie ciało potrafi rozróżniać do 10 milionów kolorów.",
        "Kiedy uczysz się czegoś nowego, w mózgu tworzą się nowe połączenia neuronowe w ułamku sekundy.",
        "Mózg może przewidywać przyszłość, budując modele prawdopodobieństwa na podstawie doświadczenia.",
        "Twoje ciało odnawia się każdą sekundę – codziennie wymienia się około 50 miliardów komórek!",
        "Podczas snu mózg przetwarza i porządkuje informacje, co pomaga w zapamiętywaniu.",
        "Człowiek może przeżyć ponad miesiąc bez jedzenia, ale bez snu maksymalnie 11 dni.",
        "Mózg stanowi tylko 2% masy ciała, ale zużywa 20% energii.",
        "Ludzkie oko może rozróżniać do 1000 odcieni szarości.",
        "Używasz 100% swojego mózgu – po prostu nie wszystkie jego części są aktywne jednocześnie.",
        "Twoja skóra odnawia się co 28 dni.",
        "Kości są twardsze niż stal. Szczególnie kość udowa, która wytrzymuje obciążenie do 900 kg!",
        "Ludzki nos może rozróżniać około 1 biliona zapachów.",
        "Twój żołądek odnawia się co 3-4 dni, aby uniknąć samostrawienia.",
        "Mózg może pracować nawet podczas snu – niektórzy ludzie znajdują rozwiązania problemów, śpiąc.",
        "Ludzkie serce kurczy się około 35 milionów razy w ciągu roku.",
        "Ludzkie kości potrafią się samodzielnie regenerować.",
        "Kiedy słuchasz ulubionej muzyki, mózg uwalnia dopaminę, wywołując uczucie szczęścia.",
        "Mózg może zmieniać swoją strukturę – to zjawisko nazywane jest neuroplastycznością.",
        "Wraz z wiekiem człowiek traci 50% kubków smakowych.",
        "Ludzki głos jest unikalny, jak odciski palców.",
        "Naczynia krwionośne w twoim ciele mogą dwukrotnie okrążyć Ziemię, gdyby je rozciągnąć w linii prostej!",
        "Śmiech aktywuje około 15 mięśni twarzy.",
        "Mózg przetwarza informacje z prędkością do 120 m/s.",
        "Człowiek potrafi rozróżniać do 500 000 różnych dźwięków.",
        "Ludzki palec jest na tyle czuły, że może wyczuć nierówność wielkości 13 nanometrów.",
        "Kiedy człowiek się zakochuje, w jego mózgu aktywują się te same obszary, co przy zażywaniu narkotyków.",
        "Ludzki mózg generuje około 70 000 myśli dziennie.",
        "Podczas śmiechu poprawia się praca układu krążenia, a poziom stresu spada.",
        "Skóra człowieka jest największym organem, jej powierzchnia wynosi do 2 metrów kwadratowych.",
        "Sen pomaga mózgowi oczyszczać się z toksyn nagromadzonych w ciągu dnia.",
        "Twoje kości są twardsze od betonu, szczególnie kość udowa.",
        "Mózg zużywa tyle samo energii, co 10-watowa żarówka.",
        "Kiedy mrugasz, twój mózg na chwilę wyłącza widzenie, ale tego nie zauważasz.",
        "Twój żołądek produkuje nowy śluz co 3-4 dni, aby chronić się przed trawieniem.",
        "Spędzasz około 10% swojego życia na mruganiu.",
        "Mózg zużywa około 20% tlenu dostarczanego do organizmu.",
        "Krew w twoim ciele porusza się z prędkością około 7 km/h.",
        "Twoje włosy rosną jeszcze przez kilka godzin po śmierci.",
        "Ludzkie ciało produkuje około litra śliny dziennie.",
        "Najsilniejszym mięśniem w organizmie jest język.",
        "Człowiek może przetrwać bez jedzenia do 40 dni, ale bez wody tylko 3-5 dni.",
        "Podczas intensywnego wysiłku fizycznego ciało może wydzielać do 4 litrów potu na godzinę.",
        "W stanie stresu źrenice rozszerzają się, aby lepiej widzieć potencjalne zagrożenie.",
        "Mózg może tworzyć wspomnienia jeszcze w łonie matki.",
        "Twoje kości są lżejsze od wody, ale niezwykle wytrzymałe.",
        "W mózgu jest więcej połączeń niż gwiazd w Drodze Mlecznej.",
        "Ludzki nos może zapamiętać do 50 000 różnych zapachów.",
        "Uczucie głodu pojawia się, gdy poziom hormonu greliny w organizmie wzrasta.",
        "Najbardziej dynamiczny mięsień w ciele to ten odpowiedzialny za mruganie.",
        "Mózg może generować nowe neurony nawet w dorosłym wieku.",
        "Każdy palec ma unikalny układ naczyń krwionośnych, jak odciski palców.",
        "Ludzki mózg może działać szybciej niż procesor superkomputera.",
        "Codziennie człowiek wykonuje średnio 20 000 oddechów.",
        "W ludzkim ciele znajduje się około 0,2 miligrama złota.",
        "Kości stają się gęstsze w odpowiedzi na aktywność fizyczną.",
        "Sen poprawia zdolność mózgu do rozwiązywania problemów.",
        "Skóra człowieka zawiera około 5 milionów receptorów bólu.",
        "Każda komórka organizmu otrzymuje składniki odżywcze z krwi w ciągu 60 sekund.",
        "Mózg uwalnia więcej endorfin podczas przytulania niż po zjedzeniu czekolady.",
        "W organizmie dorosłego człowieka znajduje się około 5 litrów krwi.",
        "Wątroba może się regenerować nawet po usunięciu 75% swojej masy.",
        "Ludzkie oczy potrafią rozróżniać ponad 500 odcieni jednego koloru.",
        "Każdy człowiek ma unikalny rytm snu i czuwania.",
        "Mózg może zapamiętać do 5 000 twarzy.",
        "Ludzkie włosy mogą wytrzymać ciężar do 100 gramów każde.",
        "Temperatura mózgu może wzrosnąć podczas intensywnej pracy umysłowej.",
        "W ciągu doby organizm traci około 500 ml wody tylko przez oddychanie.",
        "Żołądek odnawia swoją ochronną warstwę co kilka dni.",
        "Skóra człowieka regeneruje się szybciej niż jakiekolwiek inne tkanki.",
        "Ludzki jelita zawierają ponad 100 bilionów bakterii.",
        "Mózg może przetwarzać mowę w czasie krótszym niż 0,05 sekundy.",
        "Ludzkie serce może bić nawet poza ciałem, jeśli dostarczany jest tlen.",
        "Ludzki słuch może rozróżniać dźwięki o częstotliwości od 20 Hz do 20 000 Hz.",
        "Skóra potrafi wyczuć różnice temperatur już na poziomie 0,02 stopnia.",
        "Mózg lepiej zapamiętuje informacje, gdy są związane z emocjami.",
        "Ludzkie kości mogą się całkowicie regenerować po złamaniu.",
        "Ciało może dostosować się do ekstremalnych temperatur w ciągu kilku tygodni.",
        "Mózg potrafi przetwarzać obrazy widziane przez oczy w ciągu 13 milisekund.",
        "Ludzki organizm potrafi przystosować się do życia w warunkach nieważkości.",
        "Twoje ciało składa się z około 37,5 biliona komórek.",
        "Krew w organizmie odnawia się co 120 dni.",
        "Mózg produkuje wystarczająco dużo energii elektrycznej, by zasilić 10-watową żarówkę.",
        "Ludzkie włosy zawierają śladowe ilości złota.",
        "W organizmie dorosłego człowieka znajduje się około 250 gramów soli.",
        "Paznokcie rosną szybciej na dominującej ręce.",
        "Każdy człowiek ma unikalny wzór na języku, podobnie jak odciski palców.",
        "Skóra człowieka może rozciągać się dwukrotnie w stosunku do swojego normalnego rozmiaru.",
        "Ciało potrafi samo regulować temperaturę poprzez pocenie się.",
        "Ludzkie oko może przetwarzać ponad 100 klatek na sekundę.",
        "Kości mogą się całkowicie zregenerować po złamaniu bez blizn.",
        "Mózg działa jeszcze przez kilka minut po zatrzymaniu serca.",
        "W ludzkim ciele znajduje się ponad 200 różnych typów komórek.",
        "Serce pompuje ponad 7 500 litrów krwi dziennie.",
        "Ciało może produkować witaminę D pod wpływem światła słonecznego.",
        "Płuca mogą pomieścić do 6 litrów powietrza.",
        "Ludzki organizm zawiera więcej bakterii niż własnych komórek.",
        "W niskich temperaturach organizm zaczyna drżeć, aby generować ciepło.",
        "Mózg zużywa około 50% glukozy dostarczanej do organizmu.",
        "Skóra staje się jaśniejsza zimą z powodu zmniejszonej ilości melaniny.",
        "Oczy potrafią rozróżniać fale świetlne o długości od 380 do 750 nanometrów.",
        "Krew może zmieniać kolor w zależności od poziomu tlenu.",
        "Mięśnie człowieka potrafią kurczyć się z prędkością do 100 m/s.",
        "Pot sam w sobie nie ma zapachu, ale bakterie na skórze go wytwarzają.",
        "Ciało potrafi samo eliminować komórki rakowe.",
        "Impulsy nerwowe w organizmie poruszają się z prędkością do 120 m/s.",
        "Ludzki organizm może funkcjonować bez śledziony, ale osłabia to układ odpornościowy.",
        "Mózg przechowuje 2,5 petabajta informacji – tyle, co 3 miliony godzin wideo.",
        "Mięśnie mogą wytrzymać obciążenie 50 razy większe niż normalnie.",
        "Serce pompuje 200 mln litrów krwi w ciągu życia – to jak 80 basenów.",
        "90% percepcji to wzrok, ale mózg wzmacnia słuch przy jego utracie.",
        "Medytacja zagęszcza istotę szarą mózgu, poprawiając pamięć.",
        "Ciało produkuje naturalny środek przeciwbólowy 200 razy silniejszy od morfiny.",
        "Brak snu obniża zdolność zapamiętywania.",
        "Mózg szybciej reaguje na negatywne bodźce – to mechanizm ochronny.",
        "Podczas snu mózg aktywnie przetwarza i organizuje informacje.",
        "Bez jedzenia człowiek może przeżyć 60 dni, ale bez wody tylko 3.",
        "Co minutę ginie 300 mln komórek, ale tyle samo powstaje."
    ]
    
    private init() {}
    
    func getRandomFact() -> String {
        return allFacts.randomElement() ?? "Krew może zmieniać kolor w zależności od poziomu tlenu."
    }
}
