//
//  AffirmationsStorage_RU.swift
//  Persona Code
//
//  Created by Иван Семикин on 03/03/2025.
//

import Foundation

final class AffirmationsStorage_RU {
    static let shared = AffirmationsStorage_RU()
    
    private init() {}
    
    let allAffirmations: [Affirmation] = [
        // MARK: Confidence
        Affirmation(text: "Принятие себя приносит мне уверенность", category: .confidence),
        Affirmation(text: "Каждое действие ведет меня к успеху", category: .confidence),
        Affirmation(text: "Уверенность в моих решениях укрепляется", category: .confidence),
        Affirmation(text: "Каждый день приносит мне внутреннюю силу", category: .confidence),
        Affirmation(text: "Открытость к благам мира создает мне гармонию", category: .confidence),
        Affirmation(text: "Мои шаги вперед идут с уверенностью", category: .confidence),
        Affirmation(text: "Мои слова и поступки имеют значение", category: .confidence),
        Affirmation(text: "Вызовы принимаются мной с легкостью", category: .confidence),
        Affirmation(text: "Мои таланты и способности ценятся", category: .confidence),
        Affirmation(text: "Разрешение на успех приносит мне возможности", category: .confidence),
        Affirmation(text: "Моя уверенность растет с каждым днем", category: .confidence),
        Affirmation(text: "Свобода от страхов наполняет меня спокойствием", category: .confidence),
        Affirmation(text: "Мир изобилует для меня лучшим", category: .confidence),
        Affirmation(text: "Мой путь выбирается осознанно", category: .confidence),
        Affirmation(text: "Мои решения приносят мне внутреннюю силу", category: .confidence),
        Affirmation(text: "Мои действия идут с решимостью", category: .confidence),
        Affirmation(text: "Открытость к возможностям расширяет мои горизонты", category: .confidence),
        Affirmation(text: "Похвала принимается мной с благодарностью", category: .confidence),
        Affirmation(text: "Мои действия говорят громче слов", category: .confidence),
        Affirmation(text: "Мои способности находят подтверждение", category: .confidence),
        Affirmation(text: "Мои мысли выражаются легко и ясно", category: .confidence),
        Affirmation(text: "Спокойствие сохраняется во мне в любой ситуации", category: .confidence),
        Affirmation(text: "Мои цели достижимы и реальны", category: .confidence),
        Affirmation(text: "Успех и признание приходят ко мне естественно", category: .confidence),
        Affirmation(text: "Верность моим принципам приносит мне гармонию", category: .confidence),
        Affirmation(text: "Уверенность — основа моих решений", category: .confidence),
        Affirmation(text: "Моя интуиция направляет меня к правильным шагам", category: .confidence),
        Affirmation(text: "Моя уверенность вдохновляет окружающих", category: .confidence),
        Affirmation(text: "Благодарность усиливает мои достижения", category: .confidence),
        Affirmation(text: "Источник моей уверенности находится внутри", category: .confidence),
        
        // MARK: Health
        Affirmation(text: "Мое тело исцеляется и обновляется каждый день", category: .health),
        Affirmation(text: "Забота о себе приносит мне радость", category: .health),
        Affirmation(text: "Я выбираю продукты, приносящие мне силу и здоровье", category: .health),
        Affirmation(text: "Каждое дыхание наполняет меня энергией", category: .health),
        Affirmation(text: "Гармония внутри приносит мне крепкое здоровье", category: .health),
        Affirmation(text: "Мои клетки обновляются и работают на мое благо", category: .health),
        Affirmation(text: "Сон приносит мне полное восстановление", category: .health),
        Affirmation(text: "Я прислушиваюсь к потребностям своего тела", category: .health),
        Affirmation(text: "Мое тело благодарно за заботу и внимание", category: .health),
        Affirmation(text: "Я выбираю физическую активность, приносящую мне радость", category: .health),
        Affirmation(text: "Мои мысли создают мне здоровье и гармонию", category: .health),
        Affirmation(text: "Расслабление приносит мне внутренний покой", category: .health),
        Affirmation(text: "Вода очищает и наполняет меня жизненной силой", category: .health),
        Affirmation(text: "Я доверяю процессу исцеления своего тела", category: .health),
        Affirmation(text: "Мои органы и системы работают гармонично", category: .health),
        Affirmation(text: "Я выбираю привычки, укрепляющие мое здоровье", category: .health),
        Affirmation(text: "Здоровье приносит мне свободу и радость жизни", category: .health),
        Affirmation(text: "Мое тело поддерживает меня в каждом действии", category: .health),
        Affirmation(text: "Я открыт для энергии здоровья и силы", category: .health),
        Affirmation(text: "Медитация приносит мне внутренний баланс", category: .health),
        Affirmation(text: "Я отпускаю напряжение и принимаю расслабление", category: .health),
        Affirmation(text: "Забота о здоровье приносит мне удовольствие", category: .health),
        Affirmation(text: "Мой иммунитет крепнет каждый день", category: .health),
        Affirmation(text: "Я благодарен своему телу за его силы и возможности", category: .health),
        Affirmation(text: "Мое здоровье улучшается с каждым днем", category: .health),
        Affirmation(text: "Я выбираю отдых, наполняющий меня энергией", category: .health),
        Affirmation(text: "Мой разум и тело работают в гармонии", category: .health),
        Affirmation(text: "Здоровье и энергия доступны мне в полной мере", category: .health),
        Affirmation(text: "Моя любовь к себе укрепляет мое здоровье", category: .health),
        Affirmation(text: "Я открыт для новых возможностей улучшения здоровья", category: .health),
        
        // MARK: Finance
        Affirmation(text: "Финансовое изобилие доступно мне во всех сферах жизни", category: .finance),
        Affirmation(text: "Мои навыки и знания приносят мне доход", category: .finance),
        Affirmation(text: "Я привлекаю возможности для роста доходов", category: .finance),
        Affirmation(text: "Мои действия ведут меня к финансовой свободе", category: .finance),
        Affirmation(text: "Деньги приходят ко мне легко и свободно", category: .finance),
        Affirmation(text: "Я уважаю и мудро распоряжаюсь своими финансами", category: .finance),
        Affirmation(text: "Мое мышление изобилия привлекает мне достаток", category: .finance),
        Affirmation(text: "Мои финансовые цели достижимы и реальны", category: .finance),
        Affirmation(text: "Благодарность усиливает мой финансовый поток", category: .finance),
        Affirmation(text: "Я открыт для новых источников дохода", category: .finance),
        Affirmation(text: "Финансовая стабильность приносит мне уверенность", category: .finance),
        Affirmation(text: "Мои инвестиции приносят мне прибыль", category: .finance),
        Affirmation(text: "Я заслуживаю финансового успеха", category: .finance),
        Affirmation(text: "Мои доходы постоянно растут", category: .finance),
        Affirmation(text: "Мудрые решения приводят меня к процветанию", category: .finance),
        Affirmation(text: "Я легко привлекаю деньги в свою жизнь", category: .finance),
        Affirmation(text: "Финансовая свобода доступна мне с легкостью", category: .finance),
        Affirmation(text: "Я создаю источники пассивного дохода", category: .finance),
        Affirmation(text: "Мои доходы превышают мои расходы", category: .finance),
        Affirmation(text: "Мои финансы находятся под контролем", category: .finance),
        Affirmation(text: "Я выбираю финансовые возможности, приносящие мне рост", category: .finance),
        Affirmation(text: "Я доверяю процессу создания богатства", category: .finance),
        Affirmation(text: "Мои усилия вознаграждаются финансово", category: .finance),
        Affirmation(text: "Я привлекаю единомышленников для финансовых проектов", category: .finance),
        Affirmation(text: "Мои финансовые идеи приносят мне успех", category: .finance),
        Affirmation(text: "Богатство открыто для меня", category: .finance),
        Affirmation(text: "Я легко управляю своими доходами и расходами", category: .finance),
        Affirmation(text: "Финансовая дисциплина приносит мне свободу", category: .finance),
        Affirmation(text: "Я принимаю деньги с благодарностью", category: .finance),
        Affirmation(text: "Финансовое благополучие окружает меня каждый день", category: .finance),
        
        // MARK: Career
        Affirmation(text: "Моя карьера развивается успешно и гармонично", category: .career),
        Affirmation(text: "Я привлекаю возможности для карьерного роста", category: .career),
        Affirmation(text: "Мои навыки ценятся и приносят мне успех", category: .career),
        Affirmation(text: "Я достиг своих карьерных целей с уверенностью", category: .career),
        Affirmation(text: "Моя работа приносит мне радость и удовлетворение", category: .career),
        Affirmation(text: "Мои усилия вознаграждаются карьерным ростом", category: .career),
        Affirmation(text: "Я открыт для новых профессиональных вызовов", category: .career),
        Affirmation(text: "Моя экспертность укрепляет мою позицию", category: .career),
        Affirmation(text: "Моя карьера приносит мне финансовое изобилие", category: .career),
        Affirmation(text: "Я уверенно иду к вершинам карьеры", category: .career),
        Affirmation(text: "Мои достижения вдохновляют меня на новые цели", category: .career),
        Affirmation(text: "Я создаю продуктивные и гармоничные отношения на работе", category: .career),
        Affirmation(text: "Мои идеи ценятся и принимаются коллегами", category: .career),
        Affirmation(text: "Я успешно управляю своими проектами", category: .career),
        Affirmation(text: "Моя карьера соответствует моим талантам и интересам", category: .career),
        Affirmation(text: "Я нахожу баланс между работой и личной жизнью", category: .career),
        Affirmation(text: "Мои лидерские качества раскрываются естественно", category: .career),
        Affirmation(text: "Я привлекаю единомышленников для совместной работы", category: .career),
        Affirmation(text: "Моя работа приносит мне чувство значимости", category: .career),
        Affirmation(text: "Я легко справляюсь с рабочими задачами", category: .career),
        Affirmation(text: "Мои усилия направлены на достижение высот", category: .career),
        Affirmation(text: "Моя карьера развивается в нужном направлении", category: .career),
        Affirmation(text: "Я принимаю новые возможности для профессионального роста", category: .career),
        Affirmation(text: "Мои профессиональные связи приносят мне пользу", category: .career),
        Affirmation(text: "Я проявляю инициативу и решительность в работе", category: .career),
        Affirmation(text: "Моя уверенность помогает мне принимать верные решения", category: .career),
        Affirmation(text: "Я успешно прохожу все карьерные испытания", category: .career),
        Affirmation(text: "Мои цели в карьере ясны и достижимы", category: .career),
        Affirmation(text: "Я создаю позитивную репутацию в своей сфере", category: .career),
        Affirmation(text: "Моя карьера приносит мне стабильность и процветание", category: .career),
        
        // MARK: Relationships
        Affirmation(text: "Я привлекаю в свою жизнь гармоничные отношения", category: .relationships),
        Affirmation(text: "Моя открытость помогает мне строить крепкие связи", category: .relationships),
        Affirmation(text: "Я проявляю понимание и уважение в отношениях", category: .relationships),
        Affirmation(text: "Мои отношения наполняют меня радостью", category: .relationships),
        Affirmation(text: "Я открыт для новых и искренних связей", category: .relationships),
        Affirmation(text: "Моя честность создает доверие в отношениях", category: .relationships),
        Affirmation(text: "Я легко выражаю свои чувства и эмоции", category: .relationships),
        Affirmation(text: "Моя любовь приносит мне гармонию и тепло", category: .relationships),
        Affirmation(text: "Я ценю людей, которые окружают меня", category: .relationships),
        Affirmation(text: "Мои отношения основаны на взаимной поддержке", category: .relationships),
        Affirmation(text: "Я привлекаю людей, которые понимают и принимают меня", category: .relationships),
        Affirmation(text: "Моя доброта и уважение укрепляют мои связи", category: .relationships),
        Affirmation(text: "Я благодарен за гармоничные отношения в моей жизни", category: .relationships),
        Affirmation(text: "Моя интуиция помогает мне выбирать близких людей", category: .relationships),
        Affirmation(text: "Я легко иду на компромиссы, сохраняя гармонию", category: .relationships),
        Affirmation(text: "Мои слова и поступки выражают мою заботу", category: .relationships),
        Affirmation(text: "Я отпускаю обиды и прощаю искренне", category: .relationships),
        Affirmation(text: "Моя искренность привлекает ко мне честных людей", category: .relationships),
        Affirmation(text: "Я принимаю и люблю себя в отношениях", category: .relationships),
        Affirmation(text: "Мои отношения приносят мне радость и вдохновение", category: .relationships),
        Affirmation(text: "Я с легкостью привлекаю друзей и единомышленников", category: .relationships),
        Affirmation(text: "Моя поддержка и понимание важны для близких", category: .relationships),
        Affirmation(text: "Я открыто принимаю любовь и внимание", category: .relationships),
        Affirmation(text: "Мои отношения наполняют меня счастьем", category: .relationships),
        Affirmation(text: "Я привлекаю искренних и верных людей", category: .relationships),
        Affirmation(text: "Моя любовь к себе укрепляет мои отношения", category: .relationships),
        Affirmation(text: "Я с благодарностью принимаю поддержку близких", category: .relationships),
        Affirmation(text: "Моя терпимость создает гармонию в общении", category: .relationships),
        Affirmation(text: "Я отпускаю старые обиды и открываюсь новому", category: .relationships),
        Affirmation(text: "Мои отношения строятся на взаимопонимании", category: .relationships)
    ]
}
