//
//  AffirmationsStorage_PL.swift
//  Persona Code
//
//  Created by Иван Семикин on 11/03/2025.
//

import Foundation

final class AffirmationsStorage_PL {
    static let shared = AffirmationsStorage_PL()
    
    private init() {}
    
    let allAffirmations: [Affirmation] = [
        // MARK: Confidence
        Affirmation(text: "Akceptacja siebie daje mi pewność siebie", category: .confidence),
        Affirmation(text: "Każde działanie prowadzi mnie do sukcesu", category: .confidence),
        Affirmation(text: "Pewność moich decyzji wzmacnia się", category: .confidence),
        Affirmation(text: "Każdy dzień przynosi mi wewnętrzną siłę", category: .confidence),
        Affirmation(text: "Otwartość na dobro świata przynosi mi harmonię", category: .confidence),
        Affirmation(text: "Moje kroki do przodu są pełne pewności", category: .confidence),
        Affirmation(text: "Moje słowa i czyny mają znaczenie", category: .confidence),
        Affirmation(text: "Wyzwania przyjmuję z łatwością", category: .confidence),
        Affirmation(text: "Moje talenty i umiejętności są doceniane", category: .confidence),
        Affirmation(text: "Zezwolenie na sukces otwiera przede mną możliwości", category: .confidence),
        Affirmation(text: "Moja pewność siebie rośnie każdego dnia", category: .confidence),
        Affirmation(text: "Wolność od strachu wypełnia mnie spokojem", category: .confidence),
        Affirmation(text: "Świat obfituje dla mnie w to, co najlepsze", category: .confidence),
        Affirmation(text: "Moja droga jest wybierana świadomie", category: .confidence),
        Affirmation(text: "Moje decyzje przynoszą mi wewnętrzną siłę", category: .confidence),
        Affirmation(text: "Moje działania są pełne determinacji", category: .confidence),
        Affirmation(text: "Otwartość na możliwości poszerza moje horyzonty", category: .confidence),
        Affirmation(text: "Pochwały przyjmuję z wdzięcznością", category: .confidence),
        Affirmation(text: "Moje działania mówią głośniej niż słowa", category: .confidence),
        Affirmation(text: "Moje zdolności znajdują potwierdzenie", category: .confidence),
        Affirmation(text: "Moje myśli wyrażają się łatwo i jasno", category: .confidence),
        Affirmation(text: "Spokój pozostaje we mnie w każdej sytuacji", category: .confidence),
        Affirmation(text: "Moje cele są osiągalne i realne", category: .confidence),
        Affirmation(text: "Sukces i uznanie przychodzą do mnie naturalnie", category: .confidence),
        Affirmation(text: "Wierność moim zasadom przynosi mi harmonię", category: .confidence),
        Affirmation(text: "Pewność siebie to podstawa moich decyzji", category: .confidence),
        Affirmation(text: "Moja intuicja prowadzi mnie do właściwych kroków", category: .confidence),
        Affirmation(text: "Moja pewność siebie inspiruje innych", category: .confidence),
        Affirmation(text: "Wdzięczność wzmacnia moje osiągnięcia", category: .confidence),
        Affirmation(text: "Źródło mojej pewności siebie znajduje się we mnie", category: .confidence),
        
        // MARK: Health
        Affirmation(text: "Moje ciało uzdrawia się i odnawia każdego dnia", category: .health),
        Affirmation(text: "Dbając o siebie, odczuwam radość", category: .health),
        Affirmation(text: "Wybieram produkty, które dają mi siłę i zdrowie", category: .health),
        Affirmation(text: "Każdy oddech napełnia mnie energią", category: .health),
        Affirmation(text: "Harmonia wewnętrzna przynosi mi silne zdrowie", category: .health),
        Affirmation(text: "Moje komórki odnawiają się i działają dla mojego dobra", category: .health),
        Affirmation(text: "Sen daje mi pełną regenerację", category: .health),
        Affirmation(text: "Słucham potrzeb mojego ciała", category: .health),
        Affirmation(text: "Moje ciało jest wdzięczne za troskę i uwagę", category: .health),
        Affirmation(text: "Wybieram aktywność fizyczną, która sprawia mi radość", category: .health),
        Affirmation(text: "Moje myśli tworzą dla mnie zdrowie i harmonię", category: .health),
        Affirmation(text: "Relaks przynosi mi wewnętrzny spokój", category: .health),
        Affirmation(text: "Woda oczyszcza mnie i napełnia życiową siłą", category: .health),
        Affirmation(text: "Ufnie poddaję się procesowi uzdrawiania mojego ciała", category: .health),
        Affirmation(text: "Moje narządy i systemy działają harmonijnie", category: .health),
        Affirmation(text: "Wybieram nawyki, które wzmacniają moje zdrowie", category: .health),
        Affirmation(text: "Zdrowie daje mi wolność i radość życia", category: .health),
        Affirmation(text: "Moje ciało wspiera mnie w każdym działaniu", category: .health),
        Affirmation(text: "Jestem otwarty na energię zdrowia i siły", category: .health),
        Affirmation(text: "Medytacja przynosi mi wewnętrzną równowagę", category: .health),
        Affirmation(text: "Odpuszczam napięcie i przyjmuję relaks", category: .health),
        Affirmation(text: "Dbanie o zdrowie sprawia mi przyjemność", category: .health),
        Affirmation(text: "Mój układ odpornościowy staje się silniejszy każdego dnia", category: .health),
        Affirmation(text: "Jestem wdzięczny mojemu ciału za jego siłę i możliwości", category: .health),
        Affirmation(text: "Moje zdrowie poprawia się każdego dnia", category: .health),
        Affirmation(text: "Wybieram odpoczynek, który napełnia mnie energią", category: .health),
        Affirmation(text: "Mój umysł i ciało działają w harmonii", category: .health),
        Affirmation(text: "Zdrowie i energia są mi w pełni dostępne", category: .health),
        Affirmation(text: "Moja miłość do siebie wzmacnia moje zdrowie", category: .health),
        Affirmation(text: "Jestem otwarty na nowe możliwości poprawy zdrowia", category: .health),
        
        // MARK: Finance
        Affirmation(text: "Finansowa obfitość jest dostępna dla mnie we wszystkich sferach życia", category: .finance),
        Affirmation(text: "Moje umiejętności i wiedza przynoszą mi dochód", category: .finance),
        Affirmation(text: "Przyciągam możliwości zwiększenia moich dochodów", category: .finance),
        Affirmation(text: "Moje działania prowadzą mnie do wolności finansowej", category: .finance),
        Affirmation(text: "Pieniądze przychodzą do mnie łatwo i swobodnie", category: .finance),
        Affirmation(text: "Szanuję swoje finanse i mądrze nimi zarządzam", category: .finance),
        Affirmation(text: "Moje myślenie obfitości przyciąga dostatek", category: .finance),
        Affirmation(text: "Moje cele finansowe są osiągalne i realne", category: .finance),
        Affirmation(text: "Wdzięczność wzmacnia mój przepływ finansowy", category: .finance),
        Affirmation(text: "Jestem otwarty na nowe źródła dochodu", category: .finance),
        Affirmation(text: "Stabilność finansowa daje mi pewność siebie", category: .finance),
        Affirmation(text: "Moje inwestycje przynoszą mi zysk", category: .finance),
        Affirmation(text: "Zasługuję na finansowy sukces", category: .finance),
        Affirmation(text: "Moje dochody stale rosną", category: .finance),
        Affirmation(text: "Mądre decyzje prowadzą mnie do dobrobytu", category: .finance),
        Affirmation(text: "Łatwo przyciągam pieniądze do swojego życia", category: .finance),
        Affirmation(text: "Wolność finansowa jest dla mnie łatwo dostępna", category: .finance),
        Affirmation(text: "Tworzę źródła pasywnego dochodu", category: .finance),
        Affirmation(text: "Moje dochody przewyższają moje wydatki", category: .finance),
        Affirmation(text: "Moje finanse są pod pełną kontrolą", category: .finance),
        Affirmation(text: "Wybieram możliwości finansowe, które przynoszą mi wzrost", category: .finance),
        Affirmation(text: "Ufam procesowi budowania bogactwa", category: .finance),
        Affirmation(text: "Moje wysiłki są nagradzane finansowo", category: .finance),
        Affirmation(text: "Przyciągam ludzi o podobnych wartościach do projektów finansowych", category: .finance),
        Affirmation(text: "Moje pomysły finansowe przynoszą mi sukces", category: .finance),
        Affirmation(text: "Bogactwo jest dla mnie otwarte", category: .finance),
        Affirmation(text: "Łatwo zarządzam swoimi dochodami i wydatkami", category: .finance),
        Affirmation(text: "Dyscyplina finansowa przynosi mi wolność", category: .finance),
        Affirmation(text: "Przyjmuję pieniądze z wdzięcznością", category: .finance),
        Affirmation(text: "Dobrobyt finansowy otacza mnie każdego dnia", category: .finance),
        
        // MARK: Career
        Affirmation(text: "Moja kariera rozwija się pomyślnie i harmonijnie", category: .career),
        Affirmation(text: "Przyciągam możliwości rozwoju zawodowego", category: .career),
        Affirmation(text: "Moje umiejętności są cenione i przynoszą mi sukces", category: .career),
        Affirmation(text: "Osiągam swoje cele zawodowe z pewnością siebie", category: .career),
        Affirmation(text: "Moja praca daje mi radość i satysfakcję", category: .career),
        Affirmation(text: "Moje wysiłki są nagradzane awansem", category: .career),
        Affirmation(text: "Jestem otwarty na nowe wyzwania zawodowe", category: .career),
        Affirmation(text: "Moja wiedza ekspercka wzmacnia moją pozycję", category: .career),
        Affirmation(text: "Moja kariera przynosi mi finansową obfitość", category: .career),
        Affirmation(text: "Pewnie podążam na szczyt mojej kariery", category: .career),
        Affirmation(text: "Moje osiągnięcia inspirują mnie do nowych celów", category: .career),
        Affirmation(text: "Tworzę produktywne i harmonijne relacje w pracy", category: .career),
        Affirmation(text: "Moje pomysły są doceniane i akceptowane przez współpracowników", category: .career),
        Affirmation(text: "Skutecznie zarządzam swoimi projektami", category: .career),
        Affirmation(text: "Moja kariera jest zgodna z moimi talentami i zainteresowaniami", category: .career),
        Affirmation(text: "Odnajduję równowagę między pracą a życiem osobistym", category: .career),
        Affirmation(text: "Moje umiejętności przywódcze rozwijają się naturalnie", category: .career),
        Affirmation(text: "Przyciągam osoby o podobnych wartościach do współpracy", category: .career),
        Affirmation(text: "Moja praca daje mi poczucie znaczenia", category: .career),
        Affirmation(text: "Łatwo radzę sobie z zadaniami zawodowymi", category: .career),
        Affirmation(text: "Moje wysiłki są skierowane na osiągnięcie szczytów", category: .career),
        Affirmation(text: "Moja kariera rozwija się we właściwym kierunku", category: .career),
        Affirmation(text: "Akceptuję nowe możliwości rozwoju zawodowego", category: .career),
        Affirmation(text: "Moje kontakty zawodowe przynoszą mi korzyści", category: .career),
        Affirmation(text: "Wykazuję inicjatywę i determinację w pracy", category: .career),
        Affirmation(text: "Moja pewność siebie pomaga mi podejmować właściwe decyzje", category: .career),
        Affirmation(text: "Skutecznie pokonuję wszystkie wyzwania zawodowe", category: .career),
        Affirmation(text: "Moje cele zawodowe są jasne i osiągalne", category: .career),
        Affirmation(text: "Buduję pozytywną reputację w swojej branży", category: .career),
        Affirmation(text: "Moja kariera zapewnia mi stabilność i dobrobyt", category: .career),
        
        // MARK: Relationships
        Affirmation(text: "Przyciągam do swojego życia harmonijne relacje", category: .relationships),
        Affirmation(text: "Moja otwartość pomaga mi budować silne więzi", category: .relationships),
        Affirmation(text: "Okazuję zrozumienie i szacunek w relacjach", category: .relationships),
        Affirmation(text: "Moje relacje napełniają mnie radością", category: .relationships),
        Affirmation(text: "Jestem otwarty na nowe i szczere znajomości", category: .relationships),
        Affirmation(text: "Moja uczciwość buduje zaufanie w relacjach", category: .relationships),
        Affirmation(text: "Łatwo wyrażam swoje uczucia i emocje", category: .relationships),
        Affirmation(text: "Moja miłość przynosi mi harmonię i ciepło", category: .relationships),
        Affirmation(text: "Doceniam ludzi, którzy mnie otaczają", category: .relationships),
        Affirmation(text: "Moje relacje opierają się na wzajemnym wsparciu", category: .relationships),
        Affirmation(text: "Przyciągam ludzi, którzy mnie rozumieją i akceptują", category: .relationships),
        Affirmation(text: "Moja życzliwość i szacunek wzmacniają moje więzi", category: .relationships),
        Affirmation(text: "Jestem wdzięczny za harmonijne relacje w moim życiu", category: .relationships),
        Affirmation(text: "Moja intuicja pomaga mi wybierać bliskich ludzi", category: .relationships),
        Affirmation(text: "Łatwo idę na kompromisy, zachowując harmonię", category: .relationships),
        Affirmation(text: "Moje słowa i czyny wyrażają moją troskę", category: .relationships),
        Affirmation(text: "Uwalniam się od uraz i szczerze wybaczam", category: .relationships),
        Affirmation(text: "Moja szczerość przyciąga do mnie uczciwych ludzi", category: .relationships),
        Affirmation(text: "Akceptuję i kocham siebie w relacjach", category: .relationships),
        Affirmation(text: "Moje relacje przynoszą mi radość i inspirację", category: .relationships),
        Affirmation(text: "Z łatwością przyciągam przyjaciół i ludzi o podobnych wartościach", category: .relationships),
        Affirmation(text: "Moje wsparcie i zrozumienie są ważne dla bliskich", category: .relationships),
        Affirmation(text: "Otwieram się na miłość i uwagę", category: .relationships),
        Affirmation(text: "Moje relacje napełniają mnie szczęściem", category: .relationships),
        Affirmation(text: "Przyciągam szczerych i wiernych ludzi", category: .relationships),
        Affirmation(text: "Moja miłość do siebie wzmacnia moje relacje", category: .relationships),
        Affirmation(text: "Z wdzięcznością przyjmuję wsparcie bliskich", category: .relationships),
        Affirmation(text: "Moja tolerancja tworzy harmonię w komunikacji", category: .relationships),
        Affirmation(text: "Uwalniam się od dawnych uraz i otwieram się na nowe", category: .relationships),
        Affirmation(text: "Moje relacje opierają się na wzajemnym zrozumieniu", category: .relationships),
    ]
}

