//
//  AffirmationsStorage_EN.swift
//  Persona Code
//
//  Created by Иван Семикин on 11/03/2025.
//

import Foundation

final class AffirmationsStorage_EN {
    static let shared = AffirmationsStorage_EN()
    
    private init() {}
    
    let allAffirmations: [Affirmation] = [
        // MARK: Confidence
        Affirmation(text: "Self-acceptance brings me confidence", category: .confidence),
        Affirmation(text: "Every action leads me to success", category: .confidence),
        Affirmation(text: "Confidence in my decisions is growing", category: .confidence),
        Affirmation(text: "Each day brings me inner strength", category: .confidence),
        Affirmation(text: "Openness to the world's blessings creates harmony within me", category: .confidence),
        Affirmation(text: "My steps forward are taken with confidence", category: .confidence),
        Affirmation(text: "My words and actions matter", category: .confidence),
        Affirmation(text: "I embrace challenges with ease", category: .confidence),
        Affirmation(text: "My talents and abilities are valued", category: .confidence),
        Affirmation(text: "Allowing success brings me opportunities", category: .confidence),
        Affirmation(text: "My confidence grows every day", category: .confidence),
        Affirmation(text: "Freedom from fear fills me with peace", category: .confidence),
        Affirmation(text: "The world is abundant with the best for me", category: .confidence),
        Affirmation(text: "I choose my path consciously", category: .confidence),
        Affirmation(text: "My decisions bring me inner strength", category: .confidence),
        Affirmation(text: "My actions are taken with determination", category: .confidence),
        Affirmation(text: "Openness to opportunities expands my horizons", category: .confidence),
        Affirmation(text: "I receive praise with gratitude", category: .confidence),
        Affirmation(text: "My actions speak louder than words", category: .confidence),
        Affirmation(text: "My abilities are constantly validated", category: .confidence),
        Affirmation(text: "My thoughts are expressed easily and clearly", category: .confidence),
        Affirmation(text: "I remain calm in any situation", category: .confidence),
        Affirmation(text: "My goals are achievable and real", category: .confidence),
        Affirmation(text: "Success and recognition come to me naturally", category: .confidence),
        Affirmation(text: "Staying true to my principles brings me harmony", category: .confidence),
        Affirmation(text: "Confidence is the foundation of my decisions", category: .confidence),
        Affirmation(text: "My intuition guides me to the right steps", category: .confidence),
        Affirmation(text: "My confidence inspires those around me", category: .confidence),
        Affirmation(text: "Gratitude amplifies my achievements", category: .confidence),
        Affirmation(text: "The source of my confidence is within me", category: .confidence),
        
        // MARK: Health
        Affirmation(text: "My body heals and renews itself every day", category: .health),
        Affirmation(text: "Taking care of myself brings me joy", category: .health),
        Affirmation(text: "I choose foods that give me strength and health", category: .health),
        Affirmation(text: "Every breath fills me with energy", category: .health),
        Affirmation(text: "Inner harmony brings me strong health", category: .health),
        Affirmation(text: "My cells regenerate and work for my well-being", category: .health),
        Affirmation(text: "Sleep brings me complete restoration", category: .health),
        Affirmation(text: "I listen to my body’s needs", category: .health),
        Affirmation(text: "My body is grateful for care and attention", category: .health),
        Affirmation(text: "I choose physical activity that brings me joy", category: .health),
        Affirmation(text: "My thoughts create health and harmony for me", category: .health),
        Affirmation(text: "Relaxation brings me inner peace", category: .health),
        Affirmation(text: "Water cleanses and fills me with vitality", category: .health),
        Affirmation(text: "I trust the healing process of my body", category: .health),
        Affirmation(text: "My organs and systems function in harmony", category: .health),
        Affirmation(text: "I choose habits that strengthen my health", category: .health),
        Affirmation(text: "Health brings me freedom and joy in life", category: .health),
        Affirmation(text: "My body supports me in everything I do", category: .health),
        Affirmation(text: "I am open to the energy of health and strength", category: .health),
        Affirmation(text: "Meditation brings me inner balance", category: .health),
        Affirmation(text: "I release tension and embrace relaxation", category: .health),
        Affirmation(text: "Taking care of my health brings me pleasure", category: .health),
        Affirmation(text: "My immunity grows stronger every day", category: .health),
        Affirmation(text: "I am grateful to my body for its strength and abilities", category: .health),
        Affirmation(text: "My health improves with each passing day", category: .health),
        Affirmation(text: "I choose rest that fills me with energy", category: .health),
        Affirmation(text: "My mind and body work in harmony", category: .health),
        Affirmation(text: "Health and energy are fully available to me", category: .health),
        Affirmation(text: "My love for myself strengthens my health", category: .health),
        Affirmation(text: "I am open to new opportunities to improve my health", category: .health),
        
        // MARK: Finance
        Affirmation(text: "Financial abundance is available to me in all areas of life", category: .finance),
        Affirmation(text: "My skills and knowledge bring me income", category: .finance),
        Affirmation(text: "I attract opportunities for income growth", category: .finance),
        Affirmation(text: "My actions lead me to financial freedom", category: .finance),
        Affirmation(text: "Money comes to me easily and freely", category: .finance),
        Affirmation(text: "I respect and wisely manage my finances", category: .finance),
        Affirmation(text: "My abundance mindset attracts prosperity", category: .finance),
        Affirmation(text: "My financial goals are achievable and realistic", category: .finance),
        Affirmation(text: "Gratitude amplifies my financial flow", category: .finance),
        Affirmation(text: "I am open to new sources of income", category: .finance),
        Affirmation(text: "Financial stability gives me confidence", category: .finance),
        Affirmation(text: "My investments bring me profit", category: .finance),
        Affirmation(text: "I deserve financial success", category: .finance),
        Affirmation(text: "My income is constantly growing", category: .finance),
        Affirmation(text: "Wise decisions lead me to prosperity", category: .finance),
        Affirmation(text: "I effortlessly attract money into my life", category: .finance),
        Affirmation(text: "Financial freedom is easily accessible to me", category: .finance),
        Affirmation(text: "I create sources of passive income", category: .finance),
        Affirmation(text: "My income exceeds my expenses", category: .finance),
        Affirmation(text: "My finances are under control", category: .finance),
        Affirmation(text: "I choose financial opportunities that bring me growth", category: .finance),
        Affirmation(text: "I trust the process of wealth creation", category: .finance),
        Affirmation(text: "My efforts are financially rewarded", category: .finance),
        Affirmation(text: "I attract like-minded people for financial projects", category: .finance),
        Affirmation(text: "My financial ideas bring me success", category: .finance),
        Affirmation(text: "Wealth is open to me", category: .finance),
        Affirmation(text: "I easily manage my income and expenses", category: .finance),
        Affirmation(text: "Financial discipline gives me freedom", category: .finance),
        Affirmation(text: "I accept money with gratitude", category: .finance),
        Affirmation(text: "Financial well-being surrounds me every day", category: .finance),
        
        // MARK: Career
        Affirmation(text: "My career is developing successfully and harmoniously", category: .career),
        Affirmation(text: "I attract opportunities for career growth", category: .career),
        Affirmation(text: "My skills are valued and bring me success", category: .career),
        Affirmation(text: "I achieve my career goals with confidence", category: .career),
        Affirmation(text: "My work brings me joy and satisfaction", category: .career),
        Affirmation(text: "My efforts are rewarded with career growth", category: .career),
        Affirmation(text: "I am open to new professional challenges", category: .career),
        Affirmation(text: "My expertise strengthens my position", category: .career),
        Affirmation(text: "My career brings me financial abundance", category: .career),
        Affirmation(text: "I confidently climb to the top of my career", category: .career),
        Affirmation(text: "My achievements inspire me to set new goals", category: .career),
        Affirmation(text: "I build productive and harmonious work relationships", category: .career),
        Affirmation(text: "My ideas are valued and accepted by my colleagues", category: .career),
        Affirmation(text: "I successfully manage my projects", category: .career),
        Affirmation(text: "My career aligns with my talents and interests", category: .career),
        Affirmation(text: "I find balance between work and personal life", category: .career),
        Affirmation(text: "My leadership qualities develop naturally", category: .career),
        Affirmation(text: "I attract like-minded people for collaboration", category: .career),
        Affirmation(text: "My work gives me a sense of purpose", category: .career),
        Affirmation(text: "I easily handle my work tasks", category: .career),
        Affirmation(text: "My efforts are directed toward achieving great heights", category: .career),
        Affirmation(text: "My career is progressing in the right direction", category: .career),
        Affirmation(text: "I embrace new opportunities for professional growth", category: .career),
        Affirmation(text: "My professional connections benefit me", category: .career),
        Affirmation(text: "I show initiative and decisiveness in my work", category: .career),
        Affirmation(text: "My confidence helps me make the right decisions", category: .career),
        Affirmation(text: "I successfully overcome all career challenges", category: .career),
        Affirmation(text: "My career goals are clear and achievable", category: .career),
        Affirmation(text: "I build a positive reputation in my field", category: .career),
        Affirmation(text: "My career brings me stability and prosperity", category: .career),
        
        // MARK: Relationships
        Affirmation(text: "I attract harmonious relationships into my life", category: .relationships),
        Affirmation(text: "My openness helps me build strong connections", category: .relationships),
        Affirmation(text: "I show understanding and respect in relationships", category: .relationships),
        Affirmation(text: "My relationships fill me with joy", category: .relationships),
        Affirmation(text: "I am open to new and sincere connections", category: .relationships),
        Affirmation(text: "My honesty creates trust in relationships", category: .relationships),
        Affirmation(text: "I easily express my feelings and emotions", category: .relationships),
        Affirmation(text: "My love brings me harmony and warmth", category: .relationships),
        Affirmation(text: "I appreciate the people around me", category: .relationships),
        Affirmation(text: "My relationships are based on mutual support", category: .relationships),
        Affirmation(text: "I attract people who understand and accept me", category: .relationships),
        Affirmation(text: "My kindness and respect strengthen my connections", category: .relationships),
        Affirmation(text: "I am grateful for the harmonious relationships in my life", category: .relationships),
        Affirmation(text: "My intuition helps me choose the right people", category: .relationships),
        Affirmation(text: "I easily compromise while maintaining harmony", category: .relationships),
        Affirmation(text: "My words and actions express my care", category: .relationships),
        Affirmation(text: "I let go of grudges and forgive sincerely", category: .relationships),
        Affirmation(text: "My sincerity attracts honest people", category: .relationships),
        Affirmation(text: "I accept and love myself in relationships", category: .relationships),
        Affirmation(text: "My relationships bring me joy and inspiration", category: .relationships),
        Affirmation(text: "I easily attract friends and like-minded people", category: .relationships),
        Affirmation(text: "My support and understanding are valuable to my loved ones", category: .relationships),
        Affirmation(text: "I openly receive love and attention", category: .relationships),
        Affirmation(text: "My relationships fill me with happiness", category: .relationships),
        Affirmation(text: "I attract sincere and loyal people", category: .relationships),
        Affirmation(text: "My self-love strengthens my relationships", category: .relationships),
        Affirmation(text: "I gratefully accept support from my loved ones", category: .relationships),
        Affirmation(text: "My patience creates harmony in communication", category: .relationships),
        Affirmation(text: "I let go of past resentments and open myself to new experiences", category: .relationships),
        Affirmation(text: "My relationships are built on mutual understanding", category: .relationships),
    ]
}

